name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
   
    steps:
      - name: Read a variable
        run: echo "varaibale1 value is ${{ vars.variable1 }}"

      - name: Tell me a secret!
        run: echo "api key secret is  value is ${{ secrets.apikey1}}"

      - name: unset secret!
        run: echo "unknown secret is  value is ${{ secrets.doesnotexist}}"

      - name: Github stuff
        run: echo "github repo is  value is ${{ github.repository }}"

   
